### ISSUE TITLE
media-match.AMD

### ISSUE THREAD

**Issue by szepeviktor** [weblinc/media-match#12]
Please consider making your script AMD friendly:
https://github.com/umdjs/umd

Thank you!

**Comment by meowsus** [comment]
Just doing some cleanup here.

**Comment by szepeviktor** [comment]
Thank you.
So no AMD support?

**Comment by meowsus** [comment]
Since this project is pretty old and browsers are supporting matchMedia, no, there are no internal plans to enhance this library.

That's not to say I wouldn't merge a PR if you feel motivated to rewrite it :D
