### ISSUE TITLE
bower.json doesn't contain main.  Gets ignored by build steps

### ISSUE THREAD

**Issue by binarygiant** [weblinc/media-match#20]
I tried to pull the code and update the bower with a main of media.match.js, but the bower file is missing when I git checkout 09cc0dda6521a876a2a5032b6eec28743d331956.

Could you put a main into the 2.0.2 bower.json?

{
  "name": "media-match",
  "main" :"media.match.js",
  "homepage": "https://github.com/weblinc/media-match",
  "version": "2.0.2",
  "_release": "2.0.2",
  "_resolution": {
    "type": "version",
    "tag": "v2.0.2",
    "commit": "09cc0dda6521a876a2a5032b6eec28743d331956"
  },
  "_source": "git://github.com/weblinc/media-match.git",
  "_target": "~2.0.2",
  "_originalSource": "media-match"
}

**Comment by meowsus** [comment]
There ya go. Sorry about the delay!
