### ISSUE TITLE
Object doesn't support property or method 'addListener'

### ISSUE THREAD

**Issue by krissym** [weblinc/media-match#21]
I have included media.match.min.js above enquire.min.js since the enquire documentation says these two files work very well together (http://wicky.nillia.ms/enquire.js/#legacy-browsers). I'm looking for IE8/IE9 support (unfortunately).

I can not figure out what am I missing at this point? Is there a polyfill required for this media-match to work? Enquire documentation made it seem like this was the polyfill so that would make me much more confused than I am! :)

Please if anyone know!

**Comment by knightdr** [comment]
@krissym 
Could you send a code example? Are you including any other polyfills to support window.mediaMatch?

**Comment by krissym** [comment]
@knightdr I literally JUST figured out the issue. Apparently enquire conflicts with the foundation scripts as it was entering foundation rather than media-match.. So I moved the media-match script script above the foundation script and it works correctly.  Thanks for getting back to me so quickly though!
